name: Build And Deploy
on:
  push:
    branches:
      - main
      - 'release**'
env:
  SERVICE: tks-cluster-lcm
  TARGET: development
  TAG: ${{github.sha}}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    
    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          sktcloud/${{env.SERVICE}}:${{env.TAG}}

    - name: Setup Helm
      uses: hiberbee/github-action-helm@1.5.0
    - run: |
        git config --global user.email "ktkfree@github.com"
        git config --global user.name "ktkfree"

        git clone "https://${{secrets.BOT_GITHUB_TOKEN}}@github.com/openinfradev/tks-manifests.git"
        rm -rf tks-manifests/${TARGET}/${SERVICE}/manifests
        mkdir -p tks-manifests/${TARGET}/${SERVICE}/manifests
        cd tks-manifests/${TARGET}/${SERVICE}/manifests

        helm repo add openinfradev https://openinfradev.github.io/helm-repo
        helm template --set image.tag=${TAG} openinfradev/${SERVICE} > manifest.yaml

        git add manifest.yaml
        git commit --allow-empty -m "Set image tag to `${TAG}`"
        git push origin main --force
